import { requireSchoolAdmin } from "../../../db/authorization";

export async function GET(){try{const auth=await requireSchoolAdmin();if(auth.error)return auth.error;const [parents,students,classrooms,teachers,subjects,parentLinks,teacherLinks,classroomLinks,users,accountLinks]=await Promise.all([
 auth.db.prepare("SELECT id,full_name name FROM parents WHERE archived_at IS NULL ORDER BY full_name").all(),
 auth.db.prepare("SELECT s.id,s.full_name name,s.classroom_id,c.name classroom_name,c.shift_id,sh.name shift_name FROM students s LEFT JOIN classrooms c ON c.id=s.classroom_id LEFT JOIN shifts sh ON sh.id=c.shift_id WHERE s.archived_at IS NULL ORDER BY s.full_name").all(),
 auth.db.prepare("SELECT c.id,c.name,c.shift_id,sh.name shift_name FROM classrooms c LEFT JOIN shifts sh ON sh.id=c.shift_id WHERE c.archived_at IS NULL ORDER BY c.name").all(),
 auth.db.prepare("SELECT id,full_name name FROM teachers WHERE archived_at IS NULL ORDER BY full_name").all(),
 auth.db.prepare("SELECT id,name FROM subjects WHERE archived_at IS NULL ORDER BY name").all(),
 auth.db.prepare("SELECT ps.parent_id,ps.student_id,ps.relation,p.full_name parent_name,s.full_name student_name,sh.name shift_name FROM parent_students ps JOIN parents p ON p.id=ps.parent_id JOIN students s ON s.id=ps.student_id LEFT JOIN classrooms c ON c.id=s.classroom_id LEFT JOIN shifts sh ON sh.id=c.shift_id ORDER BY p.full_name").all(),
 auth.db.prepare("SELECT ts.teacher_id,ts.subject_id,t.full_name teacher_name,s.name subject_name FROM teacher_subjects ts JOIN teachers t ON t.id=ts.teacher_id JOIN subjects s ON s.id=ts.subject_id ORDER BY t.full_name").all(),
 auth.db.prepare("SELECT tc.teacher_id,tc.classroom_id,t.full_name teacher_name,c.name classroom_name FROM teacher_classrooms tc JOIN teachers t ON t.id=tc.teacher_id JOIN classrooms c ON c.id=tc.classroom_id ORDER BY t.full_name").all(),
 auth.db.prepare("SELECT id,full_name name,role FROM users WHERE status='ACTIVE' AND role IN ('TEACHER','STUDENT','PARENT') ORDER BY full_name").all(),
 auth.db.prepare("SELECT user_id,entity_type,entity_id FROM account_links").all()
 ]);return Response.json({parents:parents.results,students:students.results,classrooms:classrooms.results,teachers:teachers.results,subjects:subjects.results,parentLinks:parentLinks.results,teacherLinks:teacherLinks.results,classroomLinks:classroomLinks.results,users:users.results,accountLinks:accountLinks.results});}catch{return Response.json({error:"تعذر تحميل علاقات المدرسة"},{status:500});}}

export async function PUT(request:Request){try{const auth=await requireSchoolAdmin();if(auth.error)return auth.error;const p=await request.json() as Record<string,unknown>,action=String(p.action||"");if(action==="assign_classroom"){const studentId=Number(p.studentId),classroomId=Number(p.classroomId);const classroom=await auth.db.prepare("SELECT name FROM classrooms WHERE id=? AND archived_at IS NULL").bind(classroomId).first<{name:string}>();if(!studentId||!classroom)return Response.json({error:"الطالب أو الفصل غير صحيح"},{status:400});await auth.db.prepare("UPDATE students SET classroom_id=?,classroom_name=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND archived_at IS NULL").bind(classroomId,classroom.name,studentId).run();}
 else if(action==="link_parent"){const parentId=Number(p.parentId),studentId=Number(p.studentId),relation=String(p.relation||"ولي أمر");if(!parentId||!studentId)return Response.json({error:"اختر ولي الأمر والطالب"},{status:400});await auth.db.prepare("INSERT INTO parent_students(parent_id,student_id,relation) VALUES(?,?,?) ON CONFLICT(parent_id,student_id) DO UPDATE SET relation=excluded.relation").bind(parentId,studentId,relation).run();}
 else if(action==="unlink_parent"){await auth.db.prepare("DELETE FROM parent_students WHERE parent_id=? AND student_id=?").bind(Number(p.parentId),Number(p.studentId)).run();}
 else if(action==="link_teacher_subject"){const teacherId=Number(p.teacherId),subjectId=Number(p.subjectId);if(!teacherId||!subjectId)return Response.json({error:"اختر المعلم والمادة"},{status:400});await auth.db.prepare("INSERT OR IGNORE INTO teacher_subjects(teacher_id,subject_id) VALUES(?,?)").bind(teacherId,subjectId).run();}
 else if(action==="unlink_teacher_subject"){await auth.db.prepare("DELETE FROM teacher_subjects WHERE teacher_id=? AND subject_id=?").bind(Number(p.teacherId),Number(p.subjectId)).run();}
 else if(action==="link_teacher_classroom"){const teacherId=Number(p.teacherId),classroomId=Number(p.classroomId);if(!teacherId||!classroomId)return Response.json({error:"اختر المعلم والفصل"},{status:400});const classroom=await auth.db.prepare("SELECT shift_id FROM classrooms WHERE id=? AND archived_at IS NULL").bind(classroomId).first<{shift_id:number}>();if(!classroom?.shift_id)return Response.json({error:"عيّن الفصل إلى الفترة الصباحية أو المسائية أولاً"},{status:400});await auth.db.batch([auth.db.prepare("INSERT OR IGNORE INTO teacher_classrooms(teacher_id,classroom_id) VALUES(?,?)").bind(teacherId,classroomId),auth.db.prepare("INSERT OR IGNORE INTO teacher_shifts(teacher_id,shift_id) VALUES(?,?)").bind(teacherId,classroom.shift_id)]);}
 else if(action==="unlink_teacher_classroom"){await auth.db.prepare("DELETE FROM teacher_classrooms WHERE teacher_id=? AND classroom_id=?").bind(Number(p.teacherId),Number(p.classroomId)).run();}
 else if(action==="link_account"){const userId=Number(p.userId),entityId=Number(p.entityId),entityType=String(p.entityType||"");const user=await auth.db.prepare("SELECT role FROM users WHERE id=? AND status='ACTIVE'").bind(userId).first<{role:string}>(),expected:Record<string,string>={TEACHER:"teacher",STUDENT:"student",PARENT:"parent"};if(!user||expected[user.role]!==entityType||!entityId)return Response.json({error:"الحساب والسجل غير متوافقين"},{status:400});await auth.db.prepare("INSERT INTO account_links(user_id,entity_type,entity_id) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET entity_type=excluded.entity_type,entity_id=excluded.entity_id").bind(userId,entityType,entityId).run();}
 else if(action==="unlink_account"){await auth.db.prepare("DELETE FROM account_links WHERE user_id=?").bind(Number(p.userId)).run();}
 else return Response.json({error:"العملية غير معروفة"},{status:400});await auth.db.prepare("INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,after_data) VALUES(?,?,?,?,?)").bind(auth.record.id,"RELATION_UPDATE","school_relations",action,JSON.stringify(p)).run();return Response.json({message:"تم حفظ الربط بنجاح"});}catch{return Response.json({error:"تعذر حفظ الربط"},{status:400});}}

// شاشة «ربط الحسابات بالسجلات» ترسل بيانات الحساب والسجل مباشرة.
export async function POST(request:Request){
 const p=await request.json() as Record<string,unknown>;
 return PUT(new Request(request.url,{method:"PUT",headers:{"content-type":"application/json",cookie:request.headers.get("cookie")||""},body:JSON.stringify({...p,action:"link_account"})}));
}
