"use client";
import {useEffect,useState} from "react";
type Settings={hero_title?:string;hero_text?:string;manager_name?:string;manager_role?:string;manager_phone?:string;manager_image_url?:string;ticker_text?:string};
type Item={id:number;item_type:string;title:string;body:string;image_url:string;media_url:string;sort_order:number;published:number};
const blank={itemType:"ACHIEVER",title:"",body:"",imageUrl:"",mediaUrl:"",sortOrder:"0",published:true};
export default function PublicScreenSettings({notify}:{notify:(s:string)=>void}){
 const [settings,setSettings]=useState<Settings>({}),[items,setItems]=useState<Item[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState<Item|null>(null),[error,setError]=useState(""),[uploading,setUploading]=useState("");
 const load=()=>{setError("");fetch("/api/homepage",{cache:"no-store",headers:{"cache-control":"no-cache"}}).then(r=>r.json()).then(d=>{if(d.settings!==undefined){setSettings(d.settings||{});setItems(Array.isArray(d.items)?d.items:[])}else setError(d.error||"تعذر تحميل البطاقات القديمة")}).catch(()=>setError("تعذر تحميل البطاقات القديمة"));};
 useEffect(()=>{load()},[]);
 const send=async(p:Record<string,unknown>)=>{setError("");const payload=editing&&p.action==="create"?{...p,action:"update",id:editing.id}:p,r=await fetch("/api/homepage",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(r.ok){notify(editing?"تم تعديل البطاقة":"تم حفظ إعدادات الشاشة الرئيسية");setEditing(null);load()}else setError(d.error)};
 const edit=(x:Item)=>{setEditing(x);setForm({itemType:x.item_type,title:x.title,body:x.body,imageUrl:x.image_url,mediaUrl:x.media_url,sortOrder:String(x.sort_order),published:!!x.published});notify("تم تحميل البطاقة في نموذج الإضافة؛ عدّل البيانات ثم اضغط إضافة البطاقة للحفظ");window.scrollTo({top:0,behavior:"smooth"});};
 const upload=async(file:File,target:"manager"|"image"|"video")=>{setError("");setUploading(target);try{const data=new FormData();data.append("file",file);const r=await fetch("/api/uploads",{method:"POST",body:data}),d=await r.json();if(!r.ok)throw new Error(d.error);if(target==="manager")setSettings(s=>({...s,manager_image_url:d.url}));else setForm(f=>({...f,[target==="image"?"imageUrl":"mediaUrl"]:d.url}));notify("تم رفع الملف؛ احفظ البطاقة لإظهاره")}catch(e){setError(e instanceof Error?e.message:"تعذر رفع الملف")}finally{setUploading("")}};
 const uploadMany=async(files:FileList)=>{const urls:string[]=[];setUploading("image");try{for(const file of Array.from(files)){const data=new FormData();data.append("file",file);const r=await fetch("/api/uploads",{method:"POST",body:data}),d=await r.json();if(!r.ok)throw new Error(d.error);urls.push(d.url)}setForm(f=>({...f,imageUrl:[f.imageUrl,...urls].filter(Boolean).join("|")}));notify("تم رفع الصور؛ احفظ التقرير لإظهار المعرض")}catch(e){setError(e instanceof Error?e.message:"تعذر رفع الصور")}finally{setUploading("")}};
  return <section className="homepage-settings"><div className="panel settings-intro"><div><h2>إعدادات الشاشة الرئيسية قبل الدخول</h2><p>اختر الصور والفيديو من الجوال أو الكمبيوتر، أو استخدم رابطًا خارجيًا مثل يوتيوب.</p></div><a className="public-login" href="/showcase">معاينة الصفحة ↗</a></div>{error&&<div className="form-error">{error}</div>}
 <form className="panel settings-premium-form" onSubmit={e=>{e.preventDefault();send({action:"settings",heroTitle:settings.hero_title,heroText:settings.hero_text,managerName:settings.manager_name,managerRole:settings.manager_role,managerPhone:settings.manager_phone,managerImageUrl:settings.manager_image_url,tickerText:settings.ticker_text})}}><div className="form-section-title"><h3>واجهة المدرسة وبطاقة المدير</h3><p>تخصيص العناوين والترحيب</p></div><div className="form-grid"><label><span>عنوان الواجهة</span><input value={settings.hero_title||""} onChange={e=>setSettings({...settings,hero_title:e.target.value})}/></label><label><span>النص التعريفي</span><textarea value={settings.hero_text||""} onChange={e=>setSettings({...settings,hero_text:e.target.value})}/></label><label><span>نص الشريط الإعلاني المتحرك</span><input value={settings.ticker_text||""} onChange={e=>setSettings({...settings,ticker_text:e.target.value})}/></label><label><span>اسم المدير</span><input value={settings.manager_name||""} onChange={e=>setSettings({...settings,manager_name:e.target.value})}/></label><label><span>المسمى الوظيفي</span><input value={settings.manager_role||""} onChange={e=>setSettings({...settings,manager_role:e.target.value})}/></label><label><span>رقم التواصل</span><input inputMode="tel" value={settings.manager_phone||""} onChange={e=>setSettings({...settings,manager_phone:e.target.value})}/></label><label><span>صورة المدير من الجهاز</span><input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"manager")}/><small>{uploading==="manager"?"جارٍ رفع الصورة...":"يمكن الاختيار من الكاميرا أو المعرض"}</small></label><label><span>أو رابط صورة المدير</span><input type="url" value={settings.manager_image_url||""} onChange={e=>setSettings({...settings,manager_image_url:e.target.value})} placeholder="https://..."/></label></div><div className="settings-actions"><button className="primary">حفظ بيانات الواجهة</button></div></form>
 <form className="panel settings-premium-form" onSubmit={e=>{e.preventDefault();send({action:"create",...form});setForm(blank)}}><div className="form-section-title"><h3>إضافة محتوى</h3><p>هذه واجهة قديمة احتياطية؛ استخدم واجهة الصور والمتفوقين الجديدة.</p></div><div className="form-grid"><label><span>نوع البطاقة</span><select value={form.itemType} onChange={e=>setForm({...form,itemType:e.target.value})}><option value="NEWS">خبر أو قرار</option><option value="REPORT">تقرير مدرسي</option><option value="MEDIA">صورة أو فيديو قصير</option></select></label><label><span>العنوان</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label><span>الوصف</span><textarea value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></label><label><span>اختر صورة أو صور من الجهاز</span><input type="file" accept="image/*" multiple onChange={e=>e.target.files?.length&&uploadMany(e.target.files)}/><small>{uploading==="image"?"جارٍ رفع الصور...":"تُقبل الصور بأحجامها الأصلية"}</small></label><label><span>اختر فيديو</span><input type="file" accept="video/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"video")}/></label><label><span>روابط الصور</span><input type="text" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})}/></label><label><span>رابط فيديو / يوتيوب</span><input type="url" value={form.mediaUrl} onChange={e=>setForm({...form,mediaUrl:e.target.value})}/></label><label><span>ترتيب العرض</span><input type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> نشر مباشرة</label></div><div className="settings-actions"><button className="primary">إضافة المحتوى</button></div></form>
 <section className="panel relation-card"><h2>البطاقات الحالية</h2><div className="homepage-items">{items.map(x=><article key={x.id}><div><strong>{x.title}</strong><small>{x.item_type} • {x.published?"منشورة":"مخفية"}</small><p>{x.body}</p></div><div className="row-actions"><button type="button" className="action-link" onClick={()=>edit(x)}>تعديل</button><button type="button" className="danger" onClick={()=>send({action:"delete",id:x.id})}>حذف</button></div></article>)}{!items.length&&<p>لا توجد بطاقات محفوظة في هذه المدرسة بعد.</p>}</div></section></section>;
}
