"use client";
import {useEffect,useState} from "react";
type Settings={hero_title?:string;hero_text?:string;manager_name?:string;manager_role?:string;manager_phone?:string;manager_image_url?:string;ticker_text?:string};
type Item={id:number;item_type:string;title:string;body:string;image_url:string;media_url:string;sort_order:number;published:number};
const blank={itemType:"ACHIEVER",title:"",body:"",imageUrl:"",mediaUrl:"",sortOrder:"0",published:true};
export default function PublicScreenSettings({notify}:{notify:(s:string)=>void}){
 const [settings,setSettings]=useState<Settings>({}),[items,setItems]=useState<Item[]>([]),[form,setForm]=useState(blank),[error,setError]=useState(""),[uploading,setUploading]=useState("");
 const load=()=>fetch("/api/homepage").then(r=>r.json()).then(d=>{if(d.settings){setSettings(d.settings);setItems(d.items||[])}else setError(d.error||"تعذر التحميل")});
 useEffect(()=>{load()},[]);
 const send=async(p:Record<string,unknown>)=>{setError("");const r=await fetch("/api/homepage",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(p)}),d=await r.json();if(r.ok){notify(d.message);load()}else setError(d.error)};
 const upload=async(file:File,target:"manager"|"image"|"video")=>{setError("");setUploading(target);try{const data=new FormData();data.append("file",file);const r=await fetch("/api/uploads",{method:"POST",body:data}),d=await r.json();if(!r.ok)throw new Error(d.error);if(target==="manager")setSettings(s=>({...s,manager_image_url:d.url}));else setForm(f=>({...f,[target==="image"?"imageUrl":"mediaUrl"]:d.url}));notify("تم رفع الملف؛ احفظ البطاقة لإظهاره")}catch(e){setError(e instanceof Error?e.message:"تعذر رفع الملف")}finally{setUploading("")}};
 return <section className="homepage-settings"><div className="panel settings-intro"><div><h2>إعدادات الشاشة الرئيسية قبل الدخول</h2><p>اختر الصور والفيديو من الجوال أو الكمبيوتر، أو استخدم رابطًا خارجيًا مثل يوتيوب.</p></div><a className="public-login" href="/showcase">معاينة الصفحة ↗</a></div>{error&&<div className="form-error">{error}</div>}
 <form className="panel form-grid" onSubmit={e=>{e.preventDefault();send({action:"settings",heroTitle:settings.hero_title,heroText:settings.hero_text,managerName:settings.manager_name,managerRole:settings.manager_role,managerPhone:settings.manager_phone,managerImageUrl:settings.manager_image_url,tickerText:settings.ticker_text})}}><h2>واجهة المدرسة وبطاقة المدير</h2><label><span>عنوان الواجهة</span><input value={settings.hero_title||""} onChange={e=>setSettings({...settings,hero_title:e.target.value})}/></label><label><span>النص التعريفي</span><textarea value={settings.hero_text||""} onChange={e=>setSettings({...settings,hero_text:e.target.value})}/></label><label><span>نص الشريط الإعلاني المتحرك</span><input value={settings.ticker_text||""} onChange={e=>setSettings({...settings,ticker_text:e.target.value})}/></label><label><span>اسم المدير</span><input value={settings.manager_name||""} onChange={e=>setSettings({...settings,manager_name:e.target.value})}/></label><label><span>المسمى الوظيفي</span><input value={settings.manager_role||""} onChange={e=>setSettings({...settings,manager_role:e.target.value})}/></label><label><span>رقم التواصل</span><input inputMode="tel" value={settings.manager_phone||""} onChange={e=>setSettings({...settings,manager_phone:e.target.value})}/></label><label><span>صورة المدير من الجهاز</span><input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"manager")}/><small>{uploading==="manager"?"جارٍ رفع الصورة...":"يمكن الاختيار من الكاميرا أو المعرض"}</small></label><label><span>أو رابط صورة المدير</span><input type="url" value={settings.manager_image_url||""} onChange={e=>setSettings({...settings,manager_image_url:e.target.value})} placeholder="https://..."/></label><div className="settings-actions"><button className="primary">حفظ بيانات الواجهة</button></div></form>
 <form className="panel form-grid" onSubmit={e=>{e.preventDefault();send({action:"create",...form});setForm(blank)}}><h2>إضافة بطاقة جديدة</h2><label><span>نوع البطاقة</span><select value={form.itemType} onChange={e=>setForm({...form,itemType:e.target.value})}><option value="ACHIEVER">طالب/طالبة متفوق</option><option value="NEWS">خبر أو قرار</option><option value="REPORT">تقرير مدرسي</option><option value="MEDIA">صورة أو فيديو قصير</option></select></label><label><span>العنوان أو اسم الطالب</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label><span>الوصف</span><textarea value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="مثل: المركز الأول في الصف السادس"/></label><label><span>اختر صورة من الجهاز</span><input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"image")}/><small>{uploading==="image"?"جارٍ رفع الصورة...":"الحد الأقصى 5 ميجابايت"}</small></label><label><span>اختر فيديو قصير من الجهاز</span><input type="file" accept="video/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0],"video")}/><small>{uploading==="video"?"جارٍ رفع الفيديو...":"الحد الأقصى 15 ميجابايت"}</small></label><label><span>أو رابط صورة</span><input type="url" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})} placeholder="https://..."/></label><label><span>أو رابط فيديو / يوتيوب</span><input type="url" value={form.mediaUrl} onChange={e=>setForm({...form,mediaUrl:e.target.value})} placeholder="رابط MP4 أو يوتيوب"/></label><label><span>ترتيب العرض</span><input type="number" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> نشر مباشرة في الصفحة العامة</label><div className="settings-actions"><button className="primary">إضافة البطاقة</button></div></form>
 <section className="panel relation-card"><h2>البطاقات الحالية</h2><div className="homepage-items">{items.map(x=><article key={x.id}><div><strong>{x.title}</strong><small>{x.item_type} • {x.published?"منشورة":"مخفية"}</small><p>{x.body}</p></div><button className="danger" onClick={()=>send({action:"delete",id:x.id})}>حذف</button></article>)}{!items.length&&<p>لا توجد بطاقات بعد.</p>}</div></section></section>;
}
