"use client";
import {useMemo,useState} from "react";
type Row={name:string;detail:string;status:string;meta:string};
const sections=[
 ["dashboard","لوحة التحكم","⌂"],["students","الطلاب","♥"],["teachers","المعلمون","♦"],["classes","الفصول والمواد","▣"],["attendance","الحضور والغياب","✓"],["schedule","الجدول الدراسي","◷"],["grades","الدرجات والشهادات","★"],["fees","المصروفات","◈"],["reports","التقارير","≡"]
];
const people:Record<string,Row[]>={
 students:[{name:"سارة محمد العتيبي",detail:"الصف السادس (أ)",status:"منتظم",meta:"ST-1024"},{name:"يوسف أحمد القحطاني",detail:"الصف الخامس (ب)",status:"منتظم",meta:"ST-1025"},{name:"ليان عبدالله الغامدي",detail:"الصف الرابع (أ)",status:"منتظم",meta:"ST-1026"},{name:"عمر خالد الشهري",detail:"الصف الثالث (ج)",status:"غائب اليوم",meta:"ST-1027"}],
 teachers:[{name:"محمد علي",detail:"رياضيات",status:"متواجد",meta:"8 فصول"},{name:"نورة سعد",detail:"لغة عربية",status:"متواجد",meta:"6 فصول"},{name:"خالد حسن",detail:"علوم",status:"في حصة",meta:"7 فصول"}],
 classes:[{name:"الصف الأول (أ)",detail:"معلم الفصل: أ. هاني",status:"30 طالب",meta:"8 مواد"},{name:"الصف الثالث (ب)",detail:"معلمة الفصل: أ. نورة",status:"28 طالب",meta:"9 مواد"}]
};
const names=["سارة محمد","يوسف أحمد","ليان عبدالله","عمر خالد","نوف سعد"];
export default function SchoolApp(){
 const [active,setActive]=useState("dashboard"),[query,setQuery]=useState(""),[toast,setToast]=useState(""),[modal,setModal]=useState(false);const sec=sections.find(s=>s[0]===active)!;
 const rows=useMemo(()=>(people[active]||[]).filter(r=>(r.name+r.detail).includes(query)),[active,query]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2200)};
 return <main className="app-shell" dir="rtl"><aside className="sidebar"><div className="brand"><span className="brand-mark">ص</span><div><strong>مدرسة الصومعه</strong><small>نظام الإدارة المدرسية</small></div></div><nav>{sections.map(s=><button key={s[0]} className={active===s[0]?"active":""} onClick={()=>{setActive(s[0]);setQuery("")}}><span>{s[2]}</span>{s[1]}</button>)}</nav><div className="sidebar-footer"><button onClick={()=>notify("تم حفظ الإعدادات")}><span>⚙</span>الإعدادات</button><button onClick={()=>notify("تم تسجيل الخروج")}><span>←</span>تسجيل الخروج</button></div></aside>
 <section className="content"><header><div><h1>{sec[1]}</h1><p>{active==="dashboard"?"أهلاً بك، أحمد! إليك ملخص أداء المدرسة اليوم.":"إدارة "+sec[1]+" بسهولة ووضوح."}</p></div><div className="profile"><button className="notification" onClick={()=>notify("لديك 3 تنبيهات جديدة")}>♢<span/></button><div className="avatar">أح</div><div><strong>أحمد محمد</strong><small>مدير المدرسة</small></div></div></header>
 {active==="dashboard"?<Dashboard/>:["students","teachers","classes"].includes(active)?<><Toolbar query={query} setQuery={setQuery} label={sec[1]} add={()=>setModal(true)}/><Table rows={rows}/></>:active==="schedule"?<Schedule/>:active==="attendance"?<Attendance notify={notify}/>:active==="grades"?<Grades notify={notify}/>:active==="fees"?<Fees/>:<Reports notify={notify}/>}</section>
 {toast&&<div className="toast">✓ {toast}</div>}{modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(false)}>×</button><h2>إضافة سجل جديد</h2><label>الاسم<input placeholder="الاسم الكامل"/></label><label>التفاصيل<input placeholder="الصف أو التخصص"/></label><button className="primary" onClick={()=>{setModal(false);notify("تمت إضافة السجل بنجاح")}}>حفظ السجل</button></div></div>}</main>
}
function Toolbar({query,setQuery,label,add}:{query:string;setQuery:(s:string)=>void;label:string;add:()=>void}){return <div className="toolbar"><div className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`ابحث في ${label}...`}/></div><button className="primary" onClick={add}>+ إضافة جديد</button></div>}
function Table({rows}:{rows:Row[]}){return <div className="panel table-wrap"><table><thead><tr><th>الاسم</th><th>التفاصيل</th><th>الحالة</th><th>المعرف</th></tr></thead><tbody>{rows.map(r=><tr key={r.name}><td><span className="mini-avatar">{r.name[0]}</span><strong>{r.name}</strong></td><td>{r.detail}</td><td><span className="badge">{r.status}</span></td><td>{r.meta}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">لا توجد نتائج</div>}</div>}
function Dashboard(){let stats=[["إجمالي الطلاب","1,248","♙","blue","+12 هذا الشهر"],["المعلمون","86","♦","green","82 متواجدون"],["الفصول","32","▣","orange","6 مراحل"],["نسبة الحضور","94%","✓","red","اليوم"]];return <><div className="stats">{stats.map(s=><article className="stat" key={s[0]}><span className={`stat-icon ${s[3]}`}>{s[2]}</span><div><p>{s[0]}</p><strong>{s[1]}</strong><small>{s[4]}</small></div></article>)}</div><div className="grid"><article className="panel chart-panel"><div className="panel-title"><div><h2>نظرة عامة على الحضور</h2><p>معدل الحضور خلال الأسبوع</p></div></div><div className="chart"><div className="y-labels"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><div className="bars">{[94,92,96,89,94].map((b,i)=><div className="bar-group" key={i}><div className="bar-stack"><i style={{height:`${b}%`}}/><em style={{height:`${100-b}%`}}/></div><span>{["الأحد","الإثنين","الثلاثاء","الأربعاء","الخميس"][i]}</span></div>)}</div></div></article><article className="panel"><div className="panel-title"><div><h2>آخر الأنشطة</h2><p>آخر التحديثات في النظام</p></div></div><ul className="activities">{[["✓","تم تسجيل الحضور","الصف الثالث (أ)"],["★","تم إضافة درجات","مادة الرياضيات"],["♥","تم تسجيل طالب جديد","يوسف أحمد"]].map((a,i)=><li key={a[1]}><b className={["blue","green","orange"][i]}>{a[0]}</b><div><strong>{a[1]}</strong><p>{a[2]}</p><small>منذ {10+i*25} دقيقة</small></div></li>)}</ul></article></div></>}
function Attendance({notify}:{notify:(s:string)=>void}){const [state,setState]=useState(names.map(()=>true));return <div className="panel"><div className="filters"><select><option>الصف السادس (أ)</option></select><strong>حضور اليوم: {state.filter(Boolean).length} / 5</strong></div><div className="attendance-list">{names.map((n,i)=><div key={n}><span className="mini-avatar">{n[0]}</span><strong>{n}</strong><div className="toggle-group"><button className={state[i]?"on":""} onClick={()=>setState(s=>s.map((v,x)=>x===i?true:v))}>حاضر</button><button className={!state[i]?"off":""} onClick={()=>setState(s=>s.map((v,x)=>x===i?false:v))}>غائب</button></div></div>)}</div><button className="primary save" onClick={()=>notify("تم حفظ سجل الحضور")}>حفظ الحضور</button></div>}
function Schedule(){let days=["الأحد","الإثنين","الثلاثاء","الأربعاء","الخميس"],subs=["رياضيات","لغة عربية","علوم","لغة إنجليزية"];return <div className="panel table-wrap"><div className="filters"><select><option>الصف السادس (أ)</option></select><span>الأسبوع 12</span></div><table className="schedule"><thead><tr><th>اليوم</th><th>7:00</th><th>8:00</th><th>9:00</th><th>10:00</th></tr></thead><tbody>{days.map((d,i)=><tr key={d}><td>{d}</td>{subs.map((s,x)=><td key={s} className={`subject s${x+1}`}>{subs[(x+i)%4]}</td>)}</tr>)}</tbody></table></div>}
function Grades({notify}:{notify:(s:string)=>void}){return <div className="panel"><div className="filters"><select><option>الرياضيات</option></select><select><option>الصف السادس (أ)</option></select><button className="secondary" onClick={()=>notify("تم إصدار الشهادات")}>إصدار الشهادات</button></div><div className="grade-grid">{names.slice(0,4).map((n,i)=><label key={n}><span>{n}</span><input type="number" defaultValue={[98,91,95,87][i]}/><b>/ 100</b></label>)}</div><button className="primary save" onClick={()=>notify("تم حفظ الدرجات")}>حفظ الدرجات</button></div>}
function Fees(){return <><div className="stats">{[["إجمالي المحصل","842,500","ر.س","green"],["مبالغ مستحقة","127,300","!","red"],["نسبة التحصيل","86.9%","%","blue"]].map(s=><article className="stat" key={s[0]}><span className={`stat-icon ${s[3]}`}>{s[2]}</span><div><p>{s[0]}</p><strong>{s[1]}</strong><small>هذا الفصل</small></div></article>)}</div><Table rows={[{name:"سارة محمد",detail:"الدفعة الأولى",status:"مدفوع",meta:"3,500 ر.س"},{name:"يوسف أحمد",detail:"الدفعة الأولى",status:"مستحق",meta:"3,500 ر.س"}]}/></>}
function Reports({notify}:{notify:(s:string)=>void}){return <div className="report-grid">{[["تقرير الحضور","ملخص الحضور والغياب","✓"],["تقرير الأداء الأكاديمي","مقارنة الدرجات والنتائج","★"],["تقرير المصروفات","المدفوعات والمبالغ المستحقة","◈"],["تقرير المعلمين","الأنصبة والفصول والتقييم","♦"]].map(r=><article className="panel report-card" key={r[0]}><span>{r[2]}</span><h2>{r[0]}</h2><p>{r[1]}</p><button className="secondary" onClick={()=>notify("تم تجهيز "+r[0])}>إنشاء التقرير</button></article>)}</div>}
