import { requireSchoolAdmin } from "../../../db/authorization";
const editable=["schoolName","shortName","logoUrl","country","governorate","district","area","address","phone","email","principalName","currency","timezone","dateMode","primaryColor","academicYear","currentTerm"] as const;
const columns:Record<(typeof editable)[number],string>={schoolName:"school_name",shortName:"short_name",logoUrl:"logo_url",country:"country",governorate:"governorate",district:"district",area:"area",address:"address",phone:"phone",email:"email",principalName:"principal_name",currency:"currency",timezone:"timezone",dateMode:"date_mode",primaryColor:"primary_color",academicYear:"academic_year",currentTerm:"current_term"};
async function currentAdmin(){
 return requireSchoolAdmin();
}
function mapRow(row:Record<string,unknown>){return Object.fromEntries(editable.map(k=>[k,row[columns[k]]??""]));}
export async function GET(){try{const auth=await currentAdmin();if(auth.error)return auth.error;const row=await auth.db.prepare("SELECT * FROM school_settings WHERE id=1").first<Record<string,unknown>>();return Response.json({settings:mapRow(row??{})});}catch{return Response.json({error:"تعذر تحميل إعدادات المدرسة"},{status:500});}}
export async function PUT(request:Request){try{const auth=await currentAdmin();if(auth.error)return auth.error;const payload=await request.json() as Record<string,unknown>,name=String(payload.schoolName??"").trim();if(name.length<2||name.length>120)return Response.json({error:"اسم المدرسة يجب أن يكون بين حرفين و120 حرفًا"},{status:400});if(payload.dateMode&&!['hijri','gregorian','both'].includes(String(payload.dateMode)))return Response.json({error:"طريقة عرض التاريخ غير صحيحة"},{status:400});const before=await auth.db.prepare("SELECT * FROM school_settings WHERE id=1").first<Record<string,unknown>>(),old=mapRow(before??{}),values=editable.map(k=>String(payload[k]??old[k]??"").trim());await auth.db.prepare("UPDATE school_settings SET school_name=?,short_name=?,logo_url=?,country=?,governorate=?,district=?,area=?,address=?,phone=?,email=?,principal_name=?,currency=?,timezone=?,date_mode=?,primary_color=?,academic_year=?,current_term=?,updated_at=CURRENT_TIMESTAMP WHERE id=1").bind(...values).run();const after=await auth.db.prepare("SELECT * FROM school_settings WHERE id=1").first<Record<string,unknown>>();await auth.db.prepare("INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,before_data,after_data) VALUES(?,?,?,?,?,?)").bind(auth.record!.id,"UPDATE","school_settings","1",JSON.stringify(before),JSON.stringify(after)).run();return Response.json({settings:mapRow(after??{}),message:"تم حفظ إعدادات المدرسة"});}catch{return Response.json({error:"تعذر حفظ إعدادات المدرسة"},{status:500});}}
