import { requireSchoolAdminShift } from "../../../db/authorization";

const config={students:{table:"students",idCode:"student_number",detail:"classroom_name"},teachers:{table:"teachers",idCode:"employee_number",detail:"specialization"},classes:{table:"classrooms",idCode:"code",detail:"grade_level"},parents:{table:"parents",idCode:"parent_number",detail:"phone"},employees:{table:"employees",idCode:"employee_number",detail:"job_title"}} as const;
type Kind=keyof typeof config;
function kindOf(url:string){const value=new URL(url).searchParams.get("type") as Kind;return value&&config[value]?value:null;}
function shape(kind:Kind,row:Record<string,unknown>){const c=config[kind];return{id:Number(row.id),name:String(row[kind==="classes"?"name":"full_name"]??""),detail:String(row[c.detail]??""),status:String(row.status??"ACTIVE"),meta:String(row[c.idCode]??""),capacity:Number(row.capacity??30)};}
function scopeFilter(kind:Kind,global:boolean){if(global)return"";if(kind==="classes")return" AND shift_id=?";if(kind==="students")return" AND classroom_id IN (SELECT id FROM classrooms WHERE shift_id=?)";if(kind==="teachers")return" AND id IN (SELECT teacher_id FROM teacher_shifts WHERE shift_id=?)";if(kind==="parents")return" AND id IN (SELECT parent_id FROM parent_shifts WHERE shift_id=?)";return" AND id IN (SELECT employee_id FROM employee_shifts WHERE shift_id=?)";}
async function belongs(auth:Awaited<ReturnType<typeof requireSchoolAdminShift>>,kind:Kind,id:number){if(auth.error||auth.isGlobal)return true;const c=config[kind],filter=scopeFilter(kind,false);const row=await auth.db.prepare(`SELECT id FROM ${c.table} WHERE id=?${filter}`).bind(id,auth.activeShiftId).first();return Boolean(row);}

export async function GET(request:Request){try{const auth=await requireSchoolAdminShift();if(auth.error)return auth.error;const kind=kindOf(request.url);if(!kind)return Response.json({error:"نوع السجل غير صحيح"},{status:400});const q=new URL(request.url).searchParams.get("q")?.trim()??"",c=config[kind],name=kind==="classes"?"name":"full_name",filter=scopeFilter(kind,auth.isGlobal),bind=auth.isGlobal?[`%${q}%`,`%${q}%`]:[`%${q}%`,`%${q}%`,auth.activeShiftId];const result=await auth.db.prepare(`SELECT * FROM ${c.table} WHERE archived_at IS NULL AND (${name} LIKE ? OR ${c.idCode} LIKE ?)${filter} ORDER BY id DESC LIMIT 100`).bind(...bind).all<Record<string,unknown>>();return Response.json({items:result.results.map((row:Record<string,unknown>)=>shape(kind,row)),activeShiftId:auth.activeShiftId});}catch{return Response.json({error:"تعذر تحميل البيانات"},{status:500});}}

export async function POST(request:Request){try{const auth=await requireSchoolAdminShift();if(auth.error)return auth.error;const kind=kindOf(request.url);if(!kind)return Response.json({error:"نوع السجل غير صحيح"},{status:400});const p=await request.json() as Record<string,unknown>,name=String(p.name??"").trim(),detail=String(p.detail??"").trim(),meta=String(p.meta??"").trim();if(name.length<2||!detail||!meta)return Response.json({error:"الاسم والتفاصيل والرقم التعريفي مطلوبة"},{status:400});const c=config[kind],nameCol=kind==="classes"?"name":"full_name";let result;if(kind==="classes")result=await auth.db.prepare(`INSERT INTO classrooms(code,name,grade_level,capacity,shift_id) VALUES(?,?,?,?,?)`).bind(meta,name,detail,Number(p.capacity??30),auth.activeShiftId).run();else if(kind==="students"){const classroom=await auth.db.prepare("SELECT id,name FROM classrooms WHERE name=? AND shift_id=? AND archived_at IS NULL").bind(detail,auth.activeShiftId).first<{id:number;name:string}>();if(!classroom)return Response.json({error:"أضف الفصل أولًا، ثم اكتب اسمه كما هو في خانة الصف والفصل"},{status:400});result=await auth.db.prepare("INSERT INTO students(student_number,full_name,classroom_name,classroom_id) VALUES(?,?,?,?)").bind(meta,name,classroom.name,classroom.id).run();}else{result=await auth.db.prepare(`INSERT INTO ${c.table}(${c.idCode},${nameCol},${c.detail}) VALUES(?,?,?)`).bind(meta,name,detail).run();if(kind==="teachers")await auth.db.prepare("INSERT OR IGNORE INTO teacher_shifts(teacher_id,shift_id) VALUES(?,?)").bind(result.meta.last_row_id,auth.activeShiftId).run();if(kind==="employees")await auth.db.prepare("INSERT OR IGNORE INTO employee_shifts(employee_id,shift_id) VALUES(?,?)").bind(result.meta.last_row_id,auth.activeShiftId).run();if(kind==="parents")await auth.db.prepare("INSERT OR IGNORE INTO parent_shifts(parent_id,shift_id) VALUES(?,?)").bind(result.meta.last_row_id,auth.activeShiftId).run();}await auth.db.prepare("INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,after_data) VALUES(?,?,?,?,?)").bind(auth.record.id,"CREATE",kind,String(result.meta.last_row_id),JSON.stringify(p)).run();return Response.json({message:"تمت الإضافة في الفترة الحالية بنجاح"},{status:201});}catch(e){return Response.json({error:String(e).includes("UNIQUE")?"الرقم التعريفي مستخدم مسبقًا":"تعذر إضافة السجل"},{status:400});}}

export async function PUT(request:Request){try{const auth=await requireSchoolAdminShift();if(auth.error)return auth.error;const kind=kindOf(request.url);if(!kind)return Response.json({error:"نوع السجل غير صحيح"},{status:400});const p=await request.json() as Record<string,unknown>,id=Number(p.id),name=String(p.name??"").trim(),detail=String(p.detail??"").trim(),meta=String(p.meta??"").trim();if(!id||name.length<2||!detail||!meta)return Response.json({error:"بيانات التعديل غير مكتملة"},{status:400});if(!await belongs(auth,kind,id))return Response.json({error:"لا يمكنك تعديل سجل من الفترة الأخرى"},{status:403});const c=config[kind],nameCol=kind==="classes"?"name":"full_name",before=await auth.db.prepare(`SELECT * FROM ${c.table} WHERE id=?`).bind(id).first();if(kind==="classes")await auth.db.prepare(`UPDATE classrooms SET code=?,name=?,grade_level=?,capacity=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND archived_at IS NULL`).bind(meta,name,detail,Math.max(1,Number(p.capacity??30)),id).run();else await auth.db.prepare(`UPDATE ${c.table} SET ${c.idCode}=?,${nameCol}=?,${c.detail}=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND archived_at IS NULL`).bind(meta,name,detail,id).run();await auth.db.prepare("INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,before_data,after_data) VALUES(?,?,?,?,?,?)").bind(auth.record.id,"UPDATE",kind,String(id),JSON.stringify(before),JSON.stringify(p)).run();return Response.json({message:"تم التعديل بنجاح"});}catch(e){return Response.json({error:String(e).includes("UNIQUE")?"الرقم التعريفي مستخدم مسبقًا":"تعذر تعديل السجل"},{status:400});}}

export async function DELETE(request:Request){try{const auth=await requireSchoolAdminShift();if(auth.error)return auth.error;const kind=kindOf(request.url);if(!kind)return Response.json({error:"نوع السجل غير صحيح"},{status:400});const id=Number(new URL(request.url).searchParams.get("id"));if(!id)return Response.json({error:"المعرف مطلوب"},{status:400});if(!await belongs(auth,kind,id))return Response.json({error:"لا يمكنك أرشفة سجل من الفترة الأخرى"},{status:403});const c=config[kind],before=await auth.db.prepare(`SELECT * FROM ${c.table} WHERE id=?`).bind(id).first();await auth.db.prepare(`UPDATE ${c.table} SET archived_at=CURRENT_TIMESTAMP,status='ARCHIVED',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(id).run();await auth.db.prepare("INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,before_data) VALUES(?,?,?,?,?)").bind(auth.record.id,"ARCHIVE",kind,String(id),JSON.stringify(before)).run();return Response.json({message:"تمت أرشفة السجل"});}catch{return Response.json({error:"تعذرت أرشفة السجل"},{status:400});}}
