import { env } from "cloudflare:workers";
export async function ensureCoreSchema(){
 const db=env.DB;if(!db)throw new Error("قاعدة البيانات غير متاحة");
 await db.batch([
  db.prepare(`CREATE TABLE IF NOT EXISTS school_settings (id INTEGER PRIMARY KEY,school_name TEXT NOT NULL,short_name TEXT NOT NULL DEFAULT '',logo_url TEXT NOT NULL DEFAULT '',country TEXT NOT NULL DEFAULT 'اليمن',governorate TEXT NOT NULL DEFAULT 'لحج',district TEXT NOT NULL DEFAULT 'المفلحي',area TEXT NOT NULL DEFAULT 'يافع',address TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL DEFAULT '',email TEXT NOT NULL DEFAULT '',principal_name TEXT NOT NULL DEFAULT '',currency TEXT NOT NULL DEFAULT 'YER',timezone TEXT NOT NULL DEFAULT 'Asia/Aden',date_mode TEXT NOT NULL DEFAULT 'both',primary_color TEXT NOT NULL DEFAULT '#087b83',academic_year TEXT NOT NULL DEFAULT '1448هـ',current_term TEXT NOT NULL DEFAULT 'الفصل الأول',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT,external_user_id TEXT NOT NULL UNIQUE,email TEXT NOT NULL,full_name TEXT NOT NULL,role TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT,actor_user_id INTEGER,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,before_data TEXT,after_data TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(actor_user_id) REFERENCES users(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS roles (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,is_system INTEGER NOT NULL DEFAULT 0)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS permissions (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,module TEXT NOT NULL)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS role_permissions (role_id INTEGER NOT NULL,permission_id INTEGER NOT NULL,PRIMARY KEY(role_id,permission_id),FOREIGN KEY(role_id) REFERENCES roles(id),FOREIGN KEY(permission_id) REFERENCES permissions(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS user_roles (user_id INTEGER NOT NULL,role_id INTEGER NOT NULL,PRIMARY KEY(user_id,role_id),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(role_id) REFERENCES roles(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS students (id INTEGER PRIMARY KEY AUTOINCREMENT,student_number TEXT NOT NULL UNIQUE,full_name TEXT NOT NULL,classroom_name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',archived_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS teachers (id INTEGER PRIMARY KEY AUTOINCREMENT,employee_number TEXT NOT NULL UNIQUE,full_name TEXT NOT NULL,specialization TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',archived_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS classrooms (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,grade_level TEXT NOT NULL,capacity INTEGER NOT NULL DEFAULT 30,status TEXT NOT NULL DEFAULT 'ACTIVE',archived_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS parents (id INTEGER PRIMARY KEY AUTOINCREMENT,parent_number TEXT NOT NULL UNIQUE,full_name TEXT NOT NULL,phone TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',archived_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS employees (id INTEGER PRIMARY KEY AUTOINCREMENT,employee_number TEXT NOT NULL UNIQUE,full_name TEXT NOT NULL,job_title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',archived_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS parent_students (parent_id INTEGER NOT NULL,student_id INTEGER NOT NULL,relation TEXT NOT NULL DEFAULT 'ولي أمر',PRIMARY KEY(parent_id,student_id),FOREIGN KEY(parent_id) REFERENCES parents(id),FOREIGN KEY(student_id) REFERENCES students(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS subjects (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',archived_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS teacher_subjects (teacher_id INTEGER NOT NULL,subject_id INTEGER NOT NULL,PRIMARY KEY(teacher_id,subject_id),FOREIGN KEY(teacher_id) REFERENCES teachers(id),FOREIGN KEY(subject_id) REFERENCES subjects(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS teacher_classrooms (teacher_id INTEGER NOT NULL,classroom_id INTEGER NOT NULL,PRIMARY KEY(teacher_id,classroom_id),FOREIGN KEY(teacher_id) REFERENCES teachers(id),FOREIGN KEY(classroom_id) REFERENCES classrooms(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS account_links (user_id INTEGER PRIMARY KEY,entity_type TEXT NOT NULL,entity_id INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS academic_content (id INTEGER PRIMARY KEY AUTOINCREMENT,content_type TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,classroom_id INTEGER,subject_id INTEGER,teacher_id INTEGER,due_date TEXT,priority TEXT NOT NULL DEFAULT 'NORMAL',created_by INTEGER NOT NULL,archived_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(classroom_id) REFERENCES classrooms(id),FOREIGN KEY(subject_id) REFERENCES subjects(id),FOREIGN KEY(teacher_id) REFERENCES teachers(id),FOREIGN KEY(created_by) REFERENCES users(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS notification_reads (user_id INTEGER NOT NULL,content_id INTEGER NOT NULL,read_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,content_id),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(content_id) REFERENCES academic_content(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS assessments (id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,assessment_type TEXT NOT NULL,classroom_id INTEGER NOT NULL,subject_id INTEGER NOT NULL,teacher_id INTEGER,max_score INTEGER NOT NULL DEFAULT 100,assessment_date TEXT NOT NULL,term TEXT NOT NULL,published INTEGER NOT NULL DEFAULT 0,created_by INTEGER NOT NULL,archived_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(classroom_id) REFERENCES classrooms(id),FOREIGN KEY(subject_id) REFERENCES subjects(id),FOREIGN KEY(teacher_id) REFERENCES teachers(id),FOREIGN KEY(created_by) REFERENCES users(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS student_grades (assessment_id INTEGER NOT NULL,student_id INTEGER NOT NULL,score INTEGER NOT NULL,notes TEXT NOT NULL DEFAULT '',graded_by INTEGER NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(assessment_id,student_id),FOREIGN KEY(assessment_id) REFERENCES assessments(id),FOREIGN KEY(student_id) REFERENCES students(id),FOREIGN KEY(graded_by) REFERENCES users(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS invoices (id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_number TEXT NOT NULL UNIQUE,student_id INTEGER NOT NULL,title TEXT NOT NULL,amount INTEGER NOT NULL,due_date TEXT NOT NULL,academic_year TEXT NOT NULL,notes TEXT NOT NULL DEFAULT '',created_by INTEGER NOT NULL,cancelled_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(student_id) REFERENCES students(id),FOREIGN KEY(created_by) REFERENCES users(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS payments (id INTEGER PRIMARY KEY AUTOINCREMENT,receipt_number TEXT NOT NULL UNIQUE,invoice_id INTEGER NOT NULL,amount INTEGER NOT NULL,payment_date TEXT NOT NULL,method TEXT NOT NULL DEFAULT 'CASH',reference TEXT NOT NULL DEFAULT '',received_by INTEGER NOT NULL,reversed_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(invoice_id) REFERENCES invoices(id),FOREIGN KEY(received_by) REFERENCES users(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS shifts (id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,gender_scope TEXT NOT NULL,starts_at TEXT NOT NULL,ends_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE')`),
  db.prepare(`CREATE TABLE IF NOT EXISTS teacher_shifts (teacher_id INTEGER NOT NULL,shift_id INTEGER NOT NULL,PRIMARY KEY(teacher_id,shift_id),FOREIGN KEY(teacher_id) REFERENCES teachers(id),FOREIGN KEY(shift_id) REFERENCES shifts(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS shift_admins (user_id INTEGER NOT NULL,shift_id INTEGER NOT NULL,is_primary INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(user_id,shift_id),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(shift_id) REFERENCES shifts(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS employee_shifts (employee_id INTEGER NOT NULL,shift_id INTEGER NOT NULL,PRIMARY KEY(employee_id,shift_id),FOREIGN KEY(employee_id) REFERENCES employees(id),FOREIGN KEY(shift_id) REFERENCES shifts(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS parent_shifts (parent_id INTEGER NOT NULL,shift_id INTEGER NOT NULL,PRIMARY KEY(parent_id,shift_id),FOREIGN KEY(parent_id) REFERENCES parents(id),FOREIGN KEY(shift_id) REFERENCES shifts(id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS public_home_settings (id INTEGER PRIMARY KEY,hero_title TEXT NOT NULL DEFAULT '',hero_text TEXT NOT NULL DEFAULT '',manager_name TEXT NOT NULL DEFAULT '',manager_role TEXT NOT NULL DEFAULT 'مدير المدرسة',manager_phone TEXT NOT NULL DEFAULT '',manager_image_url TEXT NOT NULL DEFAULT '',ticker_text TEXT NOT NULL DEFAULT '',ticker_speed_seconds INTEGER NOT NULL DEFAULT 23,ticker_gap_seconds INTEGER NOT NULL DEFAULT 2,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS public_home_items (id INTEGER PRIMARY KEY AUTOINCREMENT,item_type TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL DEFAULT '',image_url TEXT NOT NULL DEFAULT '',media_url TEXT NOT NULL DEFAULT '',achiever_percentage TEXT NOT NULL DEFAULT '',achiever_average TEXT NOT NULL DEFAULT '',achiever_rank TEXT NOT NULL DEFAULT '',sort_order INTEGER NOT NULL DEFAULT 0,published INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
  db.prepare("CREATE INDEX IF NOT EXISTS idx_invoices_student ON invoices(student_id,cancelled_at)"),
  db.prepare("CREATE INDEX IF NOT EXISTS idx_payments_invoice ON payments(invoice_id,reversed_at)"),
  db.prepare("CREATE INDEX IF NOT EXISTS idx_student_grades_student ON student_grades(student_id,assessment_id)"),
  db.prepare("CREATE INDEX IF NOT EXISTS idx_academic_content_classroom ON academic_content(classroom_id,content_type,archived_at)"),
  db.prepare(`CREATE TABLE IF NOT EXISTS schedule_entries (id INTEGER PRIMARY KEY AUTOINCREMENT,classroom_id INTEGER NOT NULL,teacher_id INTEGER NOT NULL,subject_id INTEGER NOT NULL,day_of_week INTEGER NOT NULL,period_number INTEGER NOT NULL,starts_at TEXT NOT NULL,ends_at TEXT NOT NULL,FOREIGN KEY(classroom_id) REFERENCES classrooms(id),FOREIGN KEY(teacher_id) REFERENCES teachers(id),FOREIGN KEY(subject_id) REFERENCES subjects(id),UNIQUE(classroom_id,day_of_week,period_number),UNIQUE(teacher_id,day_of_week,period_number))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS attendance_records (id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL,attendance_date TEXT NOT NULL,status TEXT NOT NULL,notes TEXT NOT NULL DEFAULT '',recorded_by INTEGER,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(student_id) REFERENCES students(id),FOREIGN KEY(recorded_by) REFERENCES users(id),UNIQUE(student_id,attendance_date))`),
  db.prepare("CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type,entity_id)"),
  db.prepare("CREATE INDEX IF NOT EXISTS idx_students_name ON students(full_name)"),
  db.prepare("CREATE INDEX IF NOT EXISTS idx_teachers_name ON teachers(full_name)"),
  db.prepare("CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance_records(attendance_date)"),
 ]);
 await db.prepare(`INSERT OR IGNORE INTO school_settings (id,school_name,short_name,country,governorate,district,area,currency,timezone,date_mode,primary_color,academic_year,current_term) VALUES (1,'مدرسة الصومعه','الصومعه','اليمن','لحج','المفلحي','يافع','YER','Asia/Aden','both','#087b83','1448هـ','الفصل الأول')`).run();
 await db.prepare("INSERT OR IGNORE INTO public_home_settings(id,hero_title,hero_text,ticker_text) VALUES(1,'معًا نبني جيلاً متميزًا','أهلاً بكم في البوابة الرسمية للمدرسة؛ أخبار موثوقة، إنجازات مضيئة، وتواصل دائم مع الأسرة التعليمية.','مرحبًا بكم في بوابة المدرسة الرسمية')").run();
 await db.prepare("INSERT OR IGNORE INTO shifts(code,name,gender_scope,starts_at,ends_at) VALUES('MORNING','الفترة الصباحية','MALE','07:00','12:30')").run();
 await db.prepare("INSERT OR IGNORE INTO shifts(code,name,gender_scope,starts_at,ends_at) VALUES('EVENING','الفترة المسائية — مدرسة البنات','FEMALE','13:00','17:30')").run();
 await db.batch([
  db.prepare("INSERT OR IGNORE INTO roles(code,name,is_system) VALUES('SUPER_ADMIN','مدير النظام',1)"),db.prepare("INSERT OR IGNORE INTO roles(code,name,is_system) VALUES('ADMIN','مدير المدرسة',1)"),db.prepare("INSERT OR IGNORE INTO roles(code,name,is_system) VALUES('TEACHER','معلم',1)"),db.prepare("INSERT OR IGNORE INTO roles(code,name,is_system) VALUES('STUDENT','طالب',1)"),db.prepare("INSERT OR IGNORE INTO roles(code,name,is_system) VALUES('PARENT','ولي أمر',1)"),db.prepare("INSERT OR IGNORE INTO roles(code,name,is_system) VALUES('EMPLOYEE','موظف',1)"),
  db.prepare("INSERT OR IGNORE INTO permissions(code,name,module) VALUES('school.settings.manage','إدارة إعدادات المدرسة','settings')"),db.prepare("INSERT OR IGNORE INTO permissions(code,name,module) VALUES('users.manage','إدارة المستخدمين','users')"),db.prepare("INSERT OR IGNORE INTO permissions(code,name,module) VALUES('students.manage','إدارة الطلاب','students')"),db.prepare("INSERT OR IGNORE INTO permissions(code,name,module) VALUES('teachers.manage','إدارة المعلمين','teachers')"),db.prepare("INSERT OR IGNORE INTO permissions(code,name,module) VALUES('classes.manage','إدارة الفصول','classes')"),
  db.prepare("INSERT OR IGNORE INTO students(student_number,full_name,classroom_name) VALUES('ST-1024','سارة محمد العتيبي','الصف السادس (أ)')"),db.prepare("INSERT OR IGNORE INTO students(student_number,full_name,classroom_name) VALUES('ST-1025','يوسف أحمد القحطاني','الصف الخامس (ب)')"),
  db.prepare("INSERT OR IGNORE INTO teachers(employee_number,full_name,specialization) VALUES('T-101','محمد علي','رياضيات')"),db.prepare("INSERT OR IGNORE INTO teachers(employee_number,full_name,specialization) VALUES('T-102','نورة سعد','لغة عربية')"),
  db.prepare("INSERT OR IGNORE INTO classrooms(code,name,grade_level,capacity) VALUES('C-6A','السادس (أ)','الصف السادس',30)"),db.prepare("INSERT OR IGNORE INTO classrooms(code,name,grade_level,capacity) VALUES('C-5B','الخامس (ب)','الصف الخامس',30)"),
  db.prepare("INSERT OR IGNORE INTO parents(parent_number,full_name,phone) VALUES('P-1001','أحمد محمد الصومعي','777000001')"),db.prepare("INSERT OR IGNORE INTO employees(employee_number,full_name,job_title) VALUES('E-101','صالح عبدالله','سكرتير المدرسة')"),
  db.prepare("INSERT OR IGNORE INTO subjects(code,name) VALUES('MATH','الرياضيات')"),db.prepare("INSERT OR IGNORE INTO subjects(code,name) VALUES('AR','اللغة العربية')"),db.prepare("INSERT OR IGNORE INTO subjects(code,name) VALUES('SCI','العلوم')"),
 ]);
 const studentColumns=await db.prepare("PRAGMA table_info(students)").all<{name:string}>();
 if(!studentColumns.results.some(column=>column.name==="classroom_id"))await db.prepare("ALTER TABLE students ADD COLUMN classroom_id INTEGER REFERENCES classrooms(id)").run();
 const subjectColumns=await db.prepare("PRAGMA table_info(subjects)").all<{name:string}>();
 for(const column of ["status TEXT NOT NULL DEFAULT 'ACTIVE'","archived_at TEXT","created_at TEXT","updated_at TEXT"]){const name=column.split(" ")[0];if(!subjectColumns.results.some(item=>item.name===name))await db.prepare(`ALTER TABLE subjects ADD COLUMN ${column}`).run();}
 const userColumns=await db.prepare("PRAGMA table_info(users)").all<{name:string}>();
 for(const column of ["username TEXT","phone TEXT NOT NULL DEFAULT ''","must_change_password INTEGER NOT NULL DEFAULT 0"]){const name=column.split(" ")[0];if(!userColumns.results.some(item=>item.name===name))await db.prepare(`ALTER TABLE users ADD COLUMN ${column}`).run();}
 await db.prepare("CREATE UNIQUE INDEX IF NOT EXISTS users_username_unique ON users(username) WHERE username IS NOT NULL").run();
 const settingColumns=await db.prepare("PRAGMA table_info(school_settings)").all<{name:string}>();if(!settingColumns.results.some(item=>item.name==="work_days"))await db.prepare("ALTER TABLE school_settings ADD COLUMN work_days TEXT NOT NULL DEFAULT '[6,0,1,2,3]'").run();
 const classroomColumns=await db.prepare("PRAGMA table_info(classrooms)").all<{name:string}>();if(!classroomColumns.results.some(item=>item.name==="shift_id"))await db.prepare("ALTER TABLE classrooms ADD COLUMN shift_id INTEGER REFERENCES shifts(id)").run();
 const homeItemColumns=await db.prepare("PRAGMA table_info(public_home_items)").all<{name:string}>();
 for(const column of ["achiever_percentage TEXT NOT NULL DEFAULT ''","achiever_average TEXT NOT NULL DEFAULT ''","achiever_rank TEXT NOT NULL DEFAULT ''"]){const name=column.split(" ")[0];if(!homeItemColumns.results.some(item=>item.name===name))await db.prepare(`ALTER TABLE public_home_items ADD COLUMN ${column}`).run();}
 const homeSettingColumns=await db.prepare("PRAGMA table_info(public_home_settings)").all<{name:string}>();
 for(const column of ["ticker_speed_seconds INTEGER NOT NULL DEFAULT 23","ticker_gap_seconds INTEGER NOT NULL DEFAULT 2"]){const name=column.split(" ")[0];if(!homeSettingColumns.results.some(item=>item.name===name))await db.prepare(`ALTER TABLE public_home_settings ADD COLUMN ${column}`).run();}
 return db;
}
