import { sql } from "drizzle-orm";
import { integer, primaryKey, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const schoolSettings = sqliteTable("school_settings", {
  id: integer("id").primaryKey(), schoolName: text("school_name").notNull(), shortName: text("short_name").notNull().default(""),
  logoUrl: text("logo_url").notNull().default(""), country: text("country").notNull().default("اليمن"),
  governorate: text("governorate").notNull().default("لحج"), district: text("district").notNull().default("المفلحي"),
  area: text("area").notNull().default("يافع"), address: text("address").notNull().default(""), phone: text("phone").notNull().default(""),
  email: text("email").notNull().default(""), principalName: text("principal_name").notNull().default(""),
  currency: text("currency").notNull().default("YER"), timezone: text("timezone").notNull().default("Asia/Aden"),
  dateMode: text("date_mode", { enum: ["hijri", "gregorian", "both"] }).notNull().default("both"),
  primaryColor: text("primary_color").notNull().default("#087b83"), academicYear: text("academic_year").notNull().default("1448هـ"),
  currentTerm: text("current_term").notNull().default("الفصل الأول"), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  workDays: text("work_days").notNull().default("[6,0,1,2,3]"),
});

export const users = sqliteTable("users", {
  id: integer("id").primaryKey({ autoIncrement: true }), externalUserId: text("external_user_id").notNull(),
  email: text("email").notNull(), fullName: text("full_name").notNull(),
  role: text("role", { enum: ["SUPER_ADMIN", "ADMIN", "TEACHER", "STUDENT", "PARENT", "EMPLOYEE"] }).notNull(),
  status: text("status", { enum: ["ACTIVE", "SUSPENDED"] }).notNull().default("ACTIVE"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  username: text("username"), phone: text("phone").notNull().default(""), mustChangePassword: integer("must_change_password",{mode:"boolean"}).notNull().default(false),
}, table => [uniqueIndex("users_external_user_id_unique").on(table.externalUserId)]);

export const auditLogs = sqliteTable("audit_logs", {
  id: integer("id").primaryKey({ autoIncrement: true }), actorUserId: integer("actor_user_id").references(() => users.id),
  action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id").notNull(),
  beforeData: text("before_data"), afterData: text("after_data"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const roles = sqliteTable("roles", { id: integer("id").primaryKey({autoIncrement:true}), code:text("code").notNull(), name:text("name").notNull(), isSystem:integer("is_system",{mode:"boolean"}).notNull().default(false) }, t=>[uniqueIndex("roles_code_unique").on(t.code)]);
export const permissions = sqliteTable("permissions", { id:integer("id").primaryKey({autoIncrement:true}), code:text("code").notNull(), name:text("name").notNull(), module:text("module").notNull() }, t=>[uniqueIndex("permissions_code_unique").on(t.code)]);
export const rolePermissions = sqliteTable("role_permissions", { roleId:integer("role_id").notNull().references(()=>roles.id), permissionId:integer("permission_id").notNull().references(()=>permissions.id) });
export const userRoles = sqliteTable("user_roles", { userId:integer("user_id").notNull().references(()=>users.id), roleId:integer("role_id").notNull().references(()=>roles.id) });
export const students = sqliteTable("students", { id:integer("id").primaryKey({autoIncrement:true}), studentNumber:text("student_number").notNull(), fullName:text("full_name").notNull(), classroomName:text("classroom_name").notNull(), classroomId:integer("classroom_id"), status:text("status").notNull().default("ACTIVE"), archivedAt:text("archived_at"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[uniqueIndex("students_number_unique").on(t.studentNumber)]);
export const teachers = sqliteTable("teachers", { id:integer("id").primaryKey({autoIncrement:true}), employeeNumber:text("employee_number").notNull(), fullName:text("full_name").notNull(), specialization:text("specialization").notNull(), status:text("status").notNull().default("ACTIVE"), archivedAt:text("archived_at"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[uniqueIndex("teachers_number_unique").on(t.employeeNumber)]);
export const classrooms = sqliteTable("classrooms", { id:integer("id").primaryKey({autoIncrement:true}), code:text("code").notNull(), name:text("name").notNull(), gradeLevel:text("grade_level").notNull(), capacity:integer("capacity").notNull().default(30), shiftId:integer("shift_id"), status:text("status").notNull().default("ACTIVE"), archivedAt:text("archived_at"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[uniqueIndex("classrooms_code_unique").on(t.code)]);
export const parents = sqliteTable("parents", { id:integer("id").primaryKey({autoIncrement:true}), parentNumber:text("parent_number").notNull(), fullName:text("full_name").notNull(), phone:text("phone").notNull(), status:text("status").notNull().default("ACTIVE"), archivedAt:text("archived_at"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[uniqueIndex("parents_number_unique").on(t.parentNumber)]);
export const employees = sqliteTable("employees", { id:integer("id").primaryKey({autoIncrement:true}), employeeNumber:text("employee_number").notNull(), fullName:text("full_name").notNull(), jobTitle:text("job_title").notNull(), status:text("status").notNull().default("ACTIVE"), archivedAt:text("archived_at"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[uniqueIndex("employees_number_unique").on(t.employeeNumber)]);
export const parentStudents = sqliteTable("parent_students", { parentId:integer("parent_id").notNull().references(()=>parents.id), studentId:integer("student_id").notNull().references(()=>students.id), relation:text("relation").notNull().default("ولي أمر") },t=>[primaryKey({columns:[t.parentId,t.studentId]})]);
export const subjects = sqliteTable("subjects", { id:integer("id").primaryKey({autoIncrement:true}), code:text("code").notNull(), name:text("name").notNull(), status:text("status").notNull().default("ACTIVE"), archivedAt:text("archived_at"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[uniqueIndex("subjects_code_unique").on(t.code)]);
export const teacherSubjects = sqliteTable("teacher_subjects", { teacherId:integer("teacher_id").notNull().references(()=>teachers.id), subjectId:integer("subject_id").notNull().references(()=>subjects.id) },t=>[primaryKey({columns:[t.teacherId,t.subjectId]})]);
export const teacherClassrooms = sqliteTable("teacher_classrooms", { teacherId:integer("teacher_id").notNull().references(()=>teachers.id), classroomId:integer("classroom_id").notNull().references(()=>classrooms.id) },t=>[primaryKey({columns:[t.teacherId,t.classroomId]})]);
export const accountLinks = sqliteTable("account_links", { userId:integer("user_id").primaryKey().references(()=>users.id), entityType:text("entity_type").notNull(), entityId:integer("entity_id").notNull(), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const academicContent = sqliteTable("academic_content", { id:integer("id").primaryKey({autoIncrement:true}), contentType:text("content_type").notNull(), title:text("title").notNull(), body:text("body").notNull(), classroomId:integer("classroom_id").references(()=>classrooms.id), subjectId:integer("subject_id").references(()=>subjects.id), teacherId:integer("teacher_id").references(()=>teachers.id), dueDate:text("due_date"), priority:text("priority").notNull().default("NORMAL"), createdBy:integer("created_by").notNull().references(()=>users.id), archivedAt:text("archived_at"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const notificationReads = sqliteTable("notification_reads", { userId:integer("user_id").notNull().references(()=>users.id), contentId:integer("content_id").notNull().references(()=>academicContent.id), readAt:text("read_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[primaryKey({columns:[t.userId,t.contentId]})]);
export const assessments = sqliteTable("assessments", { id:integer("id").primaryKey({autoIncrement:true}), title:text("title").notNull(), assessmentType:text("assessment_type").notNull(), classroomId:integer("classroom_id").notNull().references(()=>classrooms.id), subjectId:integer("subject_id").notNull().references(()=>subjects.id), teacherId:integer("teacher_id").references(()=>teachers.id), maxScore:integer("max_score").notNull().default(100), assessmentDate:text("assessment_date").notNull(), term:text("term").notNull(), published:integer("published",{mode:"boolean"}).notNull().default(false), createdBy:integer("created_by").notNull().references(()=>users.id), archivedAt:text("archived_at"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const studentGrades = sqliteTable("student_grades", { assessmentId:integer("assessment_id").notNull().references(()=>assessments.id), studentId:integer("student_id").notNull().references(()=>students.id), score:integer("score").notNull(), notes:text("notes").notNull().default(""), gradedBy:integer("graded_by").notNull().references(()=>users.id), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[primaryKey({columns:[t.assessmentId,t.studentId]})]);
export const invoices = sqliteTable("invoices", { id:integer("id").primaryKey({autoIncrement:true}), invoiceNumber:text("invoice_number").notNull(), studentId:integer("student_id").notNull().references(()=>students.id), title:text("title").notNull(), amount:integer("amount").notNull(), dueDate:text("due_date").notNull(), academicYear:text("academic_year").notNull(), notes:text("notes").notNull().default(""), createdBy:integer("created_by").notNull().references(()=>users.id), cancelledAt:text("cancelled_at"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[uniqueIndex("invoices_number_unique").on(t.invoiceNumber)]);
export const payments = sqliteTable("payments", { id:integer("id").primaryKey({autoIncrement:true}), receiptNumber:text("receipt_number").notNull(), invoiceId:integer("invoice_id").notNull().references(()=>invoices.id), amount:integer("amount").notNull(), paymentDate:text("payment_date").notNull(), method:text("method").notNull().default("CASH"), reference:text("reference").notNull().default(""), receivedBy:integer("received_by").notNull().references(()=>users.id), reversedAt:text("reversed_at"), createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[uniqueIndex("payments_receipt_unique").on(t.receiptNumber)]);
export const shifts = sqliteTable("shifts", { id:integer("id").primaryKey({autoIncrement:true}), code:text("code").notNull(), name:text("name").notNull(), genderScope:text("gender_scope").notNull(), startsAt:text("starts_at").notNull(), endsAt:text("ends_at").notNull(), status:text("status").notNull().default("ACTIVE") },t=>[uniqueIndex("shifts_code_unique").on(t.code)]);
export const teacherShifts = sqliteTable("teacher_shifts", { teacherId:integer("teacher_id").notNull().references(()=>teachers.id), shiftId:integer("shift_id").notNull().references(()=>shifts.id) },t=>[primaryKey({columns:[t.teacherId,t.shiftId]})]);
export const shiftAdmins = sqliteTable("shift_admins", { userId:integer("user_id").notNull().references(()=>users.id), shiftId:integer("shift_id").notNull().references(()=>shifts.id), isPrimary:integer("is_primary",{mode:"boolean"}).notNull().default(false) },t=>[primaryKey({columns:[t.userId,t.shiftId]})]);
export const scheduleEntries = sqliteTable("schedule_entries", { id:integer("id").primaryKey({autoIncrement:true}), classroomId:integer("classroom_id").notNull().references(()=>classrooms.id), teacherId:integer("teacher_id").notNull().references(()=>teachers.id), subjectId:integer("subject_id").notNull().references(()=>subjects.id), dayOfWeek:integer("day_of_week").notNull(), periodNumber:integer("period_number").notNull(), startsAt:text("starts_at").notNull(), endsAt:text("ends_at").notNull() });
export const attendanceRecords = sqliteTable("attendance_records", { id:integer("id").primaryKey({autoIncrement:true}), studentId:integer("student_id").notNull().references(()=>students.id), attendanceDate:text("attendance_date").notNull(), status:text("status").notNull(), notes:text("notes").notNull().default(""), recordedBy:integer("recorded_by").references(()=>users.id), updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`) },t=>[uniqueIndex("attendance_student_date_unique").on(t.studentId,t.attendanceDate)]);
