"use client";
import { useState } from "react";

export default function LoginPage(){
 const [type,setType]=useState("student"),[identifier,setIdentifier]=useState(""),[password,setPassword]=useState(""),[showPassword,setShowPassword]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const submit=async(event:React.FormEvent)=>{event.preventDefault();setLoading(true);setError("");try{const response=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type,identifier,password})}),data=await response.json();if(!response.ok)throw new Error(data.error);location.href="/";}catch(e){setError(e instanceof Error?e.message:"تعذر تسجيل الدخول");}finally{setLoading(false);}};
 const hint=type==="staff"?"مثال: T101 أو بريد المعلم":type==="parent"?"اسم المستخدم أو البريد الإلكتروني":"مثال: ST1024";
 return <main className="school-login" dir="rtl"><section><div className="login-brand"><span>ص</span><div><strong>مدرسة الصومعه</strong><small>يافع — المفلحي — اليمن</small></div></div><h1 style={{fontSize:"1.75rem",fontWeight:"800",marginBottom:"0.5rem",color:"#123e43"}}>تسجيل الدخول</h1><p style={{color:"#718185",marginBottom:"1.5rem",fontSize:"0.9rem"}}>اختر نوع الحساب ثم أدخل بياناتك المدرسية للاستمرار.</p><div className="login-tabs three"><button type="button" className={type==="student"?"active":""} onClick={()=>{setType("student");setIdentifier("");setPassword("");setError("");}}>🎓 طالب</button><button type="button" className={type==="parent"?"active":""} onClick={()=>{setType("parent");setIdentifier("");setPassword("");setError("");}}>👨‍👩‍👧 ولي أمر</button><button type="button" className={type==="staff"?"active":""} onClick={()=>{setType("staff");setIdentifier("");setPassword("");setError("");}}>💼 معلم / إدارة</button></div><form onSubmit={submit} style={{display:"flex",flexDirection:"column",gap:"1rem"}}>{error&&<div className="form-error">{error}</div>}<label>اسم المستخدم (أو البريد الإلكتروني)<input required autoComplete="username" type="text" value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder={hint}/></label><label>كلمة المرور<div style={{position:"relative"}}><input required type={showPassword?"text":"password"} autoComplete="current-password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" style={{width:"100%",boxSizing:"border-box",paddingLeft:"48px"}}/><button type="button" onClick={()=>setShowPassword(!showPassword)} aria-label={showPassword?"إخفاء كلمة المرور":"إظهار كلمة المرور"} title={showPassword?"إخفاء كلمة المرور":"إظهار كلمة المرور"} style={{position:"absolute",left:"8px",top:"50%",transform:"translateY(-50%)",border:"0",background:"transparent",cursor:"pointer",fontSize:"1.2rem",padding:"4px"}}>{showPassword?"◉":"◌"}</button></div></label><button className="primary" disabled={loading}>{loading?"جاري التحقق...":"تسجيل الدخول"}</button></form><div style={{marginTop:"1.5rem",textAlign:"center"}}><small className="login-help">إذا نسيت بيانات الدخول، يرجى التواصل مع إدارة المدرسة لإصدار كلمة مرور مؤقتة جديدة.</small></div></section></main>;
}
