import { requireSchoolAdminShift } from "../../../../db/authorization";
import { createExternalUser, externalAuthConfigured, parentEmail, restoreExternalUser, staffEmail, studentEmail, updateExternalUser, validPassword } from "../../../../db/external-auth";
export async function GET(){const auth=await requireSchoolAdminShift();if(auth.error)return auth.error;const shift=auth.activeShiftId,[users,students,parents]=await Promise.all([auth.db.prepare(`SELECT u.id,u.full_name name,u.role,u.username,u.email,u.phone FROM users u LEFT JOIN account_links al ON al.user_id=u.id WHERE u.status='ACTIVE' AND (u.role NOT IN ('STUDENT','PARENT') OR (u.role='STUDENT' AND al.entity_type='student' AND al.entity_id IN (SELECT st.id FROM students st JOIN classrooms c ON c.id=st.classroom_id WHERE c.shift_id=?)) OR (u.role='PARENT' AND al.entity_type='parent' AND al.entity_id IN (SELECT p.id FROM parents p WHERE EXISTS(SELECT 1 FROM parent_shifts ps WHERE ps.parent_id=p.id AND ps.shift_id=?) OR EXISTS(SELECT 1 FROM parent_students pp JOIN students st ON st.id=pp.student_id JOIN classrooms c ON c.id=st.classroom_id WHERE pp.parent_id=p.id AND c.shift_id=?)))) ORDER BY u.full_name`).bind(shift,shift,shift).all(),auth.db.prepare("SELECT st.id,st.full_name name,st.student_number meta FROM students st JOIN classrooms c ON c.id=st.classroom_id WHERE st.archived_at IS NULL AND c.shift_id=? ORDER BY st.full_name").bind(shift).all(),auth.db.prepare("SELECT p.id,p.full_name name,p.phone meta FROM parents p WHERE p.archived_at IS NULL AND (EXISTS(SELECT 1 FROM parent_shifts ps WHERE ps.parent_id=p.id AND ps.shift_id=?) OR EXISTS(SELECT 1 FROM parent_students pp JOIN students st ON st.id=pp.student_id JOIN classrooms c ON c.id=st.classroom_id WHERE pp.parent_id=p.id AND c.shift_id=?)) ORDER BY p.full_name").bind(shift,shift).all()]);return Response.json({configured:externalAuthConfigured(),users:users.results,students:students.results,parents:parents.results,currentUserId:auth.record.id,currentRole:auth.record.role,activeShiftId:shift});}
export async function POST(request:Request){try{
 const auth=await requireSchoolAdminShift();if(auth.error)return auth.error;
 const p=await request.json() as Record<string,unknown>,role=String(p.role||""),providedUsername=String(p.username||"").trim(),password=String(p.password||""),fullName=String(p.fullName||"").trim(),phone=String(p.phone||"").trim(),entityId=Number(p.entityId),phoneLogin=phone.replace(/\D/g,""),username=role==="PARENT"?(phoneLogin||providedUsername||`parent${entityId}`).toLowerCase():providedUsername;
 if(role==="ADMIN"&&auth.record.role!=="SUPER_ADMIN")return Response.json({error:"مدير النظام فقط يستطيع إنشاء نائب مدير"},{status:403});
 const staff=["TEACHER","ADMIN"].includes(role),requestedEmail=String(p.email||"").trim().toLowerCase(),email=role==="STUDENT"?studentEmail(username):staff?staffEmail(username):requestedEmail||parentEmail(username);
 if(!["STUDENT","PARENT","TEACHER","ADMIN"].includes(role)||fullName.split(/\s+/).length<3||!validPassword(password)||(!entityId&&role!=="ADMIN")||!/^[A-Za-z0-9._-]{3,30}$/.test(username)||(role==="PARENT"&&phoneLogin.length<7))return Response.json({error:"تحقق من الاسم الثلاثي ورقم الجوال وكلمة المرور"},{status:400});
 if(role==="STUDENT"&&!await auth.db.prepare("SELECT st.id FROM students st JOIN classrooms c ON c.id=st.classroom_id WHERE st.id=? AND c.shift_id=?").bind(entityId,auth.activeShiftId).first())return Response.json({error:"الطالب ليس ضمن الفترة الحالية"},{status:403});
 if(role==="PARENT"&&!await auth.db.prepare("SELECT p.id FROM parents p WHERE p.id=? AND (EXISTS(SELECT 1 FROM parent_shifts ps WHERE ps.parent_id=p.id AND ps.shift_id=?) OR EXISTS(SELECT 1 FROM parent_students pp JOIN students st ON st.id=pp.student_id JOIN classrooms c ON c.id=st.classroom_id WHERE pp.parent_id=p.id AND c.shift_id=?))").bind(entityId,auth.activeShiftId,auth.activeShiftId).first())return Response.json({error:"ولي الأمر ليس مرتبطًا بالفترة الحالية"},{status:403});
 if(role==="PARENT"){const existing=await auth.db.prepare("SELECT id FROM users WHERE role='PARENT' AND phone=? LIMIT 1").bind(phone).first();if(existing)return Response.json({error:"رقم الهاتف موجود مسبقًا لحساب ولي أمر آخر"},{status:409});}
 let external;try{external=await createExternalUser(email,password,{full_name:fullName,role,username,must_change_password:true});}catch(e){if(role!=="ADMIN"||!/(already|registered|exists)/i.test(e instanceof Error?e.message:""))throw e;external=await restoreExternalUser(email,password,{full_name:fullName,role:"ADMIN",username,must_change_password:true});}
 const saved=await auth.db.prepare("SELECT id FROM users WHERE lower(email)=? OR lower(username)=? LIMIT 1").bind(email.toLowerCase(),username.toLowerCase()).first<{id:number}>();
 let userId:number;if(saved){userId=saved.id;await auth.db.prepare("UPDATE users SET external_user_id=?,email=?,full_name=?,role=?,status='ACTIVE',username=?,phone=?,must_change_password=1,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(external.id,email,fullName,role,username,phone,userId).run();}else{const result=await auth.db.prepare("INSERT INTO users(external_user_id,email,full_name,role,status,username,phone,must_change_password) VALUES(?,?,?,?,?,?,?,1)").bind(external.id,email,fullName,role,"ACTIVE",username,phone).run();userId=Number(result.meta.last_row_id);}
 if(entityId)await auth.db.prepare("INSERT INTO account_links(user_id,entity_type,entity_id) VALUES(?,?,?)").bind(userId,role==="STUDENT"?"student":role==="PARENT"?"parent":"teacher",entityId).run();
 return Response.json({message:role==="PARENT"?`تم إنشاء الحساب. اسم دخول ولي الأمر: ${username}`:role==="ADMIN"?"تمت استعادة حساب مدير الفترة وربطه":"تم إنشاء الحساب الخارجي وربطه بالملف",id:userId,username:role==="PARENT"?username:undefined},{status:201});
 }catch(e){return Response.json({error:e instanceof Error?e.message:"تعذر إنشاء الحساب"},{status:400});}}
export async function PUT(request:Request){try{
 const auth=await requireSchoolAdminShift();if(auth.error)return auth.error;
 const p=await request.json() as Record<string,unknown>,id=Number(p.id),password=String(p.password||""),email=String(p.email||"").trim().toLowerCase(),role=String(p.role||""),user=await auth.db.prepare("SELECT external_user_id,role FROM users WHERE id=?").bind(id).first<{external_user_id:string;role:string}>();if(!user)return Response.json({error:"الحساب غير موجود"},{status:404});
 if(user.role==="STUDENT"&&!await auth.db.prepare("SELECT u.id FROM users u JOIN account_links al ON al.user_id=u.id JOIN students st ON st.id=al.entity_id JOIN classrooms c ON c.id=st.classroom_id WHERE u.id=? AND al.entity_type='student' AND c.shift_id=?").bind(id,auth.activeShiftId).first())return Response.json({error:"حساب الطالب ليس ضمن الفترة الحالية"},{status:403});
 if(user.role==="PARENT"&&!await auth.db.prepare("SELECT u.id FROM users u JOIN account_links al ON al.user_id=u.id WHERE u.id=? AND al.entity_type='parent' AND (EXISTS(SELECT 1 FROM parent_shifts ps WHERE ps.parent_id=al.entity_id AND ps.shift_id=?) OR EXISTS(SELECT 1 FROM parent_students pp JOIN students st ON st.id=pp.student_id JOIN classrooms c ON c.id=st.classroom_id WHERE pp.parent_id=al.entity_id AND c.shift_id=?))").bind(id,auth.activeShiftId,auth.activeShiftId).first())return Response.json({error:"حساب ولي الأمر ليس ضمن الفترة الحالية"},{status:403});
 if(role==="ADMIN"&&auth.record.role!=="SUPER_ADMIN")return Response.json({error:"مدير النظام فقط يستطيع منح صلاحية نائب المدير"},{status:403});
 const changes:Record<string,unknown>={};if(password){if(!validPassword(password))return Response.json({error:"كلمة المرور يجب أن تكون 8 خانات وبها حرف كبير وصغير ورقم"},{status:400});changes.password=password;changes.user_metadata={must_change_password:true};}if(email&&user.role==="PARENT")changes.email=email;if(!Object.keys(changes).length&&!role)return Response.json({error:"لا توجد تغييرات"},{status:400});
 if(Object.keys(changes).length)await updateExternalUser(user.external_user_id,changes);if(email&&user.role==="PARENT")await auth.db.prepare("UPDATE users SET email=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(email,id).run();if(password)await auth.db.prepare("UPDATE users SET must_change_password=1,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(id).run();if(role&&["TEACHER","ADMIN"].includes(role))await auth.db.prepare("UPDATE users SET role=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(role,id).run();
 await auth.db.prepare("INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,after_data) VALUES(?,?,?,?,?)").bind(auth.record.id,role?"DELEGATE_ADMIN":"RESET_CREDENTIALS","users",String(id),JSON.stringify({emailChanged:Boolean(email),passwordReset:Boolean(password),role:role||undefined})).run();return Response.json({message:role==="ADMIN"?"تم منح صلاحية نائب المدير":"تم تحديث بيانات الدخول"});
 }catch(e){return Response.json({error:e instanceof Error?e.message:"تعذر تحديث بيانات الدخول"},{status:400});}}
export async function DELETE(request:Request){try{
 const auth=await requireSchoolAdminShift();if(auth.error)return auth.error;
 if(auth.record.role!=="SUPER_ADMIN")return Response.json({error:"هذه العملية خاصة بدائرة التطوير"},{status:403});
 const p=await request.json() as Record<string,unknown>,id=Number(p.id);
 if(!id||id===auth.record.id)return Response.json({error:"لا يمكن إلغاء حساب مشرف النظام الحالي"},{status:400});
 const user=await auth.db.prepare("SELECT id,full_name,role FROM users WHERE id=? AND status='ACTIVE'").bind(id).first<{id:number;full_name:string;role:string}>();
 if(!user)return Response.json({error:"الحساب غير موجود أو موقوف"},{status:404});
 if(user.role!=="ADMIN")return Response.json({error:"يمكن إلغاء حسابات مديري الفترات فقط من هنا"},{status:400});
 await auth.db.prepare("DELETE FROM shift_admins WHERE user_id=?").bind(id).run();
 await auth.db.prepare("UPDATE users SET status='SUSPENDED',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(id).run();
 await auth.db.prepare("INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,after_data) VALUES(?,?,?,?,?)").bind(auth.record.id,"SUSPEND_MANAGER","users",String(id),JSON.stringify({fullName:user.full_name})).run();
 return Response.json({message:"تم إلغاء حساب المدير وإزالته من الفترات. يمكن استعادته لاحقًا من قاعدة البيانات عند الحاجة."});
 }catch{return Response.json({error:"تعذر إلغاء حساب المدير"},{status:400});}}
