import { requireSchoolAdmin } from "../../../../db/authorization";
import { createExternalUser, externalAuthConfigured, parentEmail, staffEmail, studentEmail, updateExternalUser, validPassword } from "../../../../db/external-auth";
export async function GET(){const auth=await requireSchoolAdmin();if(auth.error)return auth.error;const users=await auth.db.prepare("SELECT id,full_name name,role,username,email FROM users WHERE status='ACTIVE' ORDER BY full_name").all();return Response.json({configured:externalAuthConfigured(),users:users.results,currentUserId:auth.record.id,currentRole:auth.record.role});}
export async function POST(request:Request){try{
 const auth=await requireSchoolAdmin();if(auth.error)return auth.error;
 const p=await request.json() as Record<string,unknown>,role=String(p.role||""),providedUsername=String(p.username||"").trim(),password=String(p.password||""),fullName=String(p.fullName||"").trim(),phone=String(p.phone||"").trim(),entityId=Number(p.entityId),phoneLogin=phone.replace(/\D/g,""),username=role==="PARENT"?(phoneLogin||providedUsername||`parent${entityId}`).toLowerCase():providedUsername;
 if(role==="ADMIN"&&auth.record.role!=="SUPER_ADMIN")return Response.json({error:"مدير النظام فقط يستطيع إنشاء نائب مدير"},{status:403});
 const staff=["TEACHER","ADMIN"].includes(role),requestedEmail=String(p.email||"").trim().toLowerCase(),email=role==="STUDENT"?studentEmail(username):staff?staffEmail(username):requestedEmail||parentEmail(username);
 if(!["STUDENT","PARENT","TEACHER","ADMIN"].includes(role)||fullName.split(/\s+/).length<3||!validPassword(password)||(!entityId&&role!=="ADMIN")||!/^[A-Za-z0-9._-]{3,30}$/.test(username)||(role==="PARENT"&&phoneLogin.length<7))return Response.json({error:"تحقق من الاسم الثلاثي ورقم الجوال وكلمة المرور"},{status:400});
 if(role==="PARENT"){const existing=await auth.db.prepare("SELECT id FROM users WHERE role='PARENT' AND phone=? LIMIT 1").bind(phone).first();if(existing)return Response.json({error:"رقم الهاتف موجود مسبقًا لحساب ولي أمر آخر"},{status:409});}
 const external=await createExternalUser(email,password,{full_name:fullName,role,username,must_change_password:true}),result=await auth.db.prepare("INSERT INTO users(external_user_id,email,full_name,role,status,username,phone,must_change_password) VALUES(?,?,?,?,?,?,?,1)").bind(external.id,email,fullName,role,"ACTIVE",username,phone).run();
 if(entityId)await auth.db.prepare("INSERT INTO account_links(user_id,entity_type,entity_id) VALUES(?,?,?)").bind(result.meta.last_row_id,role==="STUDENT"?"student":role==="PARENT"?"parent":"teacher",entityId).run();
 return Response.json({message:role==="PARENT"?`تم إنشاء الحساب. اسم دخول ولي الأمر: ${username}`:role==="ADMIN"?"تم إنشاء حساب مدير الفترة":"تم إنشاء الحساب الخارجي وربطه بالملف",id:result.meta.last_row_id,username:role==="PARENT"?username:undefined},{status:201});
 }catch(e){return Response.json({error:e instanceof Error?e.message:"تعذر إنشاء الحساب"},{status:400});}}
export async function PUT(request:Request){try{
 const auth=await requireSchoolAdmin();if(auth.error)return auth.error;
 const p=await request.json() as Record<string,unknown>,id=Number(p.id),password=String(p.password||""),email=String(p.email||"").trim().toLowerCase(),role=String(p.role||""),user=await auth.db.prepare("SELECT external_user_id,role FROM users WHERE id=?").bind(id).first<{external_user_id:string;role:string}>();if(!user)return Response.json({error:"الحساب غير موجود"},{status:404});
 if(role==="ADMIN"&&auth.record.role!=="SUPER_ADMIN")return Response.json({error:"مدير النظام فقط يستطيع منح صلاحية نائب المدير"},{status:403});
 const changes:Record<string,unknown>={};if(password){if(!validPassword(password))return Response.json({error:"كلمة المرور يجب أن تكون 8 خانات وبها حرف كبير وصغير ورقم"},{status:400});changes.password=password;changes.user_metadata={must_change_password:true};}if(email&&user.role==="PARENT")changes.email=email;if(!Object.keys(changes).length&&!role)return Response.json({error:"لا توجد تغييرات"},{status:400});
 if(Object.keys(changes).length)await updateExternalUser(user.external_user_id,changes);if(email&&user.role==="PARENT")await auth.db.prepare("UPDATE users SET email=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(email,id).run();if(password)await auth.db.prepare("UPDATE users SET must_change_password=1,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(id).run();if(role&&["TEACHER","ADMIN"].includes(role))await auth.db.prepare("UPDATE users SET role=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(role,id).run();
 await auth.db.prepare("INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,after_data) VALUES(?,?,?,?,?)").bind(auth.record.id,role?"DELEGATE_ADMIN":"RESET_CREDENTIALS","users",String(id),JSON.stringify({emailChanged:Boolean(email),passwordReset:Boolean(password),role:role||undefined})).run();return Response.json({message:role==="ADMIN"?"تم منح صلاحية نائب المدير":"تم تحديث بيانات الدخول"});
 }catch(e){return Response.json({error:e instanceof Error?e.message:"تعذر تحديث بيانات الدخول"},{status:400});}}
