import { requireSchoolAdmin } from "../../../db/authorization";
export async function GET(){try{const auth=await requireSchoolAdmin();if(auth.error)return auth.error;if(auth.record.role!=="SUPER_ADMIN")return Response.json({error:"إدارة الفترات خاصة بدائرة التطوير"},{status:403});const [settings,shifts,teachers,admins,teacherLinks,adminLinks,classrooms]=await Promise.all([auth.db.prepare("SELECT work_days FROM school_settings WHERE id=1").first<{work_days:string}>(),auth.db.prepare("SELECT * FROM shifts WHERE status='ACTIVE' ORDER BY id").all(),auth.db.prepare("SELECT id,full_name name FROM teachers WHERE archived_at IS NULL ORDER BY full_name").all(),auth.db.prepare("SELECT id,full_name name,role FROM users WHERE status='ACTIVE' AND role IN ('SUPER_ADMIN','ADMIN') ORDER BY full_name").all(),auth.db.prepare("SELECT ts.teacher_id,ts.shift_id,t.full_name teacher_name,s.name shift_name FROM teacher_shifts ts JOIN teachers t ON t.id=ts.teacher_id JOIN shifts s ON s.id=ts.shift_id ORDER BY s.id,t.full_name").all(),auth.db.prepare("SELECT sa.user_id,sa.shift_id,sa.is_primary,u.full_name admin_name,s.name shift_name FROM shift_admins sa JOIN users u ON u.id=sa.user_id JOIN shifts s ON s.id=sa.shift_id ORDER BY s.id").all(),auth.db.prepare("SELECT c.id,c.name,c.shift_id,s.name shift_name FROM classrooms c LEFT JOIN shifts s ON s.id=c.shift_id WHERE c.archived_at IS NULL ORDER BY c.name").all()]);return Response.json({workDays:JSON.parse(settings?.work_days||"[6,0,1,2,3]"),shifts:shifts.results,teachers:teachers.results,admins:admins.results,teacherLinks:teacherLinks.results,adminLinks:adminLinks.results,classrooms:classrooms.results});}catch{return Response.json({error:"تعذر تحميل إعدادات الفترات"},{status:500});}}
export async function PUT(request:Request){try{const auth=await requireSchoolAdmin();if(auth.error)return auth.error;if(auth.record.role!=="SUPER_ADMIN")return Response.json({error:"إدارة الفترات خاصة بدائرة التطوير"},{status:403});const p=await request.json() as Record<string,unknown>,action=String(p.action||"");if(action==="work_days"){const days=Array.isArray(p.days)?p.days.map(Number).filter(x=>x>=0&&x<=6):[];if(!days.length)return Response.json({error:"اختر يوم عمل واحدًا على الأقل"},{status:400});await auth.db.prepare("UPDATE school_settings SET work_days=?,updated_at=CURRENT_TIMESTAMP WHERE id=1").bind(JSON.stringify([...new Set(days)])).run();}
 else if(action==="update_shift"){const id=Number(p.id),name=String(p.name||"").trim(),gender=String(p.genderScope||"");if(!id||!name||!["MALE","FEMALE","MIXED"].includes(gender))return Response.json({error:"بيانات الفترة غير صحيحة"},{status:400});await auth.db.prepare("UPDATE shifts SET name=?,gender_scope=?,starts_at=?,ends_at=? WHERE id=?").bind(name,gender,String(p.startsAt||"07:00"),String(p.endsAt||"12:30"),id).run();}
 else if(action==="teacher"){await auth.db.prepare("INSERT OR IGNORE INTO teacher_shifts(teacher_id,shift_id) VALUES(?,?)").bind(Number(p.teacherId),Number(p.shiftId)).run();}
 else if(action==="remove_teacher"){await auth.db.prepare("DELETE FROM teacher_shifts WHERE teacher_id=? AND shift_id=?").bind(Number(p.teacherId),Number(p.shiftId)).run();}
 else if(action==="admin"){await auth.db.prepare("INSERT INTO shift_admins(user_id,shift_id,is_primary) VALUES(?,?,1) ON CONFLICT(user_id,shift_id) DO UPDATE SET is_primary=1").bind(Number(p.userId),Number(p.shiftId)).run();}
 else if(action==="remove_admin"){await auth.db.prepare("DELETE FROM shift_admins WHERE user_id=? AND shift_id=?").bind(Number(p.userId),Number(p.shiftId)).run();}
 else if(action==="classroom"){await auth.db.prepare("UPDATE classrooms SET shift_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(Number(p.shiftId),Number(p.classroomId)).run();}
 else return Response.json({error:"العملية غير معروفة"},{status:400});await auth.db.prepare("INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,after_data) VALUES(?,?,?,?,?)").bind(auth.record.id,"UPDATE","shifts",action,JSON.stringify(p)).run();return Response.json({message:"تم حفظ إعدادات الفترات"});}catch{return Response.json({error:"تعذر حفظ إعدادات الفترات"},{status:400});}}
