import { requireSchoolAdmin } from "../../../db/authorization";
export async function GET(){try{const auth=await requireSchoolAdmin();if(auth.error)return auth.error;const [students,teachers,classrooms,attendance,grades,finance,audit]=await Promise.all([
 auth.db.prepare("SELECT COUNT(*) total FROM students WHERE archived_at IS NULL").first<{total:number}>(),
 auth.db.prepare("SELECT COUNT(*) total FROM teachers WHERE archived_at IS NULL").first<{total:number}>(),
 auth.db.prepare("SELECT COUNT(*) total FROM classrooms WHERE archived_at IS NULL").first<{total:number}>(),
 auth.db.prepare(`SELECT attendance_date,COUNT(*) total,SUM(CASE WHEN status='PRESENT' THEN 1 ELSE 0 END) present,SUM(CASE WHEN status='ABSENT' THEN 1 ELSE 0 END) absent,SUM(CASE WHEN status='LATE' THEN 1 ELSE 0 END) late,ROUND(SUM(CASE WHEN status='PRESENT' THEN 1 ELSE 0 END)*100.0/COUNT(*),1) rate FROM attendance_records GROUP BY attendance_date ORDER BY attendance_date DESC LIMIT 14`).all(),
 auth.db.prepare(`SELECT s.name subject_name,COUNT(*) graded,ROUND(AVG(g.score*100.0/a.max_score),1) average,MAX(ROUND(g.score*100.0/a.max_score,1)) highest,MIN(ROUND(g.score*100.0/a.max_score,1)) lowest FROM student_grades g JOIN assessments a ON a.id=g.assessment_id JOIN subjects s ON s.id=a.subject_id WHERE a.archived_at IS NULL GROUP BY s.id ORDER BY average DESC`).all(),
 auth.db.prepare(`SELECT COALESCE(SUM(i.amount),0) invoiced,COALESCE((SELECT SUM(amount) FROM payments WHERE reversed_at IS NULL),0) collected,COALESCE(SUM(i.amount),0)-COALESCE((SELECT SUM(amount) FROM payments WHERE reversed_at IS NULL),0) balance FROM invoices i WHERE i.cancelled_at IS NULL`).first(),
 auth.db.prepare(`SELECT l.id,l.action,l.entity_type,l.entity_id,l.created_at,u.full_name actor_name FROM audit_logs l LEFT JOIN users u ON u.id=l.actor_user_id ORDER BY l.id DESC LIMIT 100`).all()
 ]);return Response.json({summary:{students:Number(students?.total||0),teachers:Number(teachers?.total||0),classrooms:Number(classrooms?.total||0),attendanceRate:Number((attendance.results[0] as Record<string,unknown>)?.rate||0),averageGrade:Number((grades.results[0] as Record<string,unknown>)?.average||0),invoiced:Number((finance as Record<string,unknown>)?.invoiced||0),collected:Number((finance as Record<string,unknown>)?.collected||0),balance:Number((finance as Record<string,unknown>)?.balance||0)},attendance:attendance.results,grades:grades.results,audit:audit.results});}catch{return Response.json({error:"تعذر إعداد التقارير"},{status:500});}}
